platform :ios, '7.0'

target "Injector", :exclusive => true do
  # pod "EEEInjector"
  # pod "EEEOperationCenter", :path => "../"
end

target "InjectorTests", :exclusive => true do
  pod "Kiwi/XCTest"
end
